In [1]:
"""
Question 1: 
    You would have to use a method that is less influenced by the number of features.
    You could use a Gradient Descent, like Stochastic Gradient Descent or Mini-batch gradient descent
    
Question 2: 
    The difference in scale would cause the cost function look like a long shallow bowl. This would cause
    Gradient Descent algorithms to converge slowly, as they would need more "jumps." A simple solution is 
    to scale features to fit more uniformly.Using an algorithm like SVD or Natural Equation would not benifit 
    from scaling. Regularized models could also suffer without scaling because the larger values would cause
    lower ones to be ignored

Question 3:
    No, because the model would would appear convex, not concave.
    
Question 4:
    For methods like Linear Regression and Logistic Regression using gradient descent, if done right the models 
    can be made to be very over time. This requires the a small learning rate. Another Point is that even if you
    let a Stochastic GD or Minibatch GD run for a long time, they would still produce models that are a little different

Question 5:
    This could be the result of overfitting or diverging. If you notice the training error is not going up, that
    means that the model is overfitting. If the training error is also going up, then that is a sign that the learning
    rate is too high, causing the diversion
  
Question 6:
    No, the algorithm makes jumps randomly, so not all iterations make positive progress.

Question 7:
    Stochastic Gradient Descent will get close to the optimal solution fastest. Batch Gradient Descent would actually be
    able to converge. One way to improve the convergence of Stochastic Gradient Descent is to slowly lower the training rate
    as it gets closer to the optimum. That would prevent it from iterating around in the area without making progres.
    
Question 8:
    Overfitting can cause gaps between training error and validation error, esspecially if training error does not increase.
    You could decrease the degree of the model, regularize the model, or increase the training size.

Question 9:
    If both are high then the system has a high variance. This is typical of underfitting. the hyperparameter a should be reduced
    because the model is too regular. 
    
Question 10:
    As long as regularization is used properly, it tends to improve models. Over regularized models underfit, and unregularized models
    can easily overfit.
    This descision depends on the scenario; simply put, if the model has many unneccessary features lasso will automatically render them out
    If you think that all of the features should be important for your dataset, you should use Ridge Regression.
    Yes, Elastic Net is typically better than Lasso. The downside is that it is more complicated 

Question 11:
    Two logistic regressors would be best, since there are four possibilities. out-day, out-night, in-day, in-night.
    
"""
"Question 12: "

'Question 12: '

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())

['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

In [3]:
import numpy as np
X = iris["data"][:, (2, 3)]  #length and width of petals
y = iris["target"]
biasX = np.c_[np.ones([len(X), 1]), X]

In [4]:
totalLen = len(biasX)
totalLen # how much data are we working with

150

In [5]:
testSetLen = int(0.2 * totalLen)
testSetLen # we should set aside 20% of the data. How much is that

30

In [6]:
validationSetLen = int(0.2 * totalLen)
validationSetLen # we should set aside 20% of the data. How much is that

30

In [7]:
trainingSetLen = totalLen - testSetLen - validationSetLen
trainingSetLen # 80% left to train on. How much is that

90

In [8]:
randomized = np.random.permutation(totalLen) #randomize indecies in the hopes of even sampling

In [9]:
XTraining = biasX[randomized[:trainingSetLen]] # grab 0-90 random items for training
yTraining = y[randomized[:trainingSetLen]] # grab 0-90 random items for training
XValidation = biasX[randomized[trainingSetLen:-validationSetLen]]# grab 30 random items for validation
yValidation = y[randomized[trainingSetLen:-validationSetLen]]# grab 30 random items for validation
XTest = biasX[randomized[-testSetLen:]]# grab 30 random items for testing
yTest = y[randomized[-testSetLen:]]# grab 30 random itemsfor testing
# Note that this is a random mapping method. the randomness is decided once and then related to the the iterable arrays
# If you would choose random elements for each, there would be repeated data and unused data

In [10]:
def oneHotCoverter(vectorIn):
    numberOfClasses = vectorIn.max() + 1 
    vectorLength = len(vectorIn)
    oneHotMatrixOut = np.zeros((vectorLength, numberOfClasses))
    oneHotMatrixOut[np.arange(vectorLength), vectorIn] = 1
    return oneHotMatrixOut

In [11]:
yTraining

array([2, 0, 2, 1, 1, 2, 1, 2, 0, 1, 0, 2, 1, 2, 2, 0, 2, 0, 2, 1, 0, 0,
       2, 0, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 0, 1, 1, 2, 1, 0, 2, 0, 0, 2,
       2, 1, 1, 1, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2, 2,
       1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 0, 1, 0, 0, 1, 1,
       0, 1])

In [12]:
oneHotCoverter(yTraining)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [13]:
oneHotTest = oneHotCoverter(yTest)
oneHotYValidation = oneHotCoverter(yValidation)
oneHotYTraining = oneHotCoverter(yTraining)

In [14]:
def softmax(logits):
    exps = np.exp(logits)
    exp_sums = np.sum(exps, axis=1, keepdims=True)
    return exps / exp_sums

In [15]:
numOfInputs = XTraining.shape[1]
numOfOutputs = len(np.unique(yTraining))

In [16]:
# Formulas come from chapter, and I looked to the solutions to get implementation ideas
eta = 0.1     #Fairly High, since we will be employing stopping early
numIterations = 5001
m = len(XTraining)
epsilon = 1e-7
alpha = 0.1  # regularization hyperparamer
bestLoss = np.infty # used for early stopping


Theta = np.random.randn(numOfInputs, numOfOutputs)

for iteration in range(numIterations):
    logits = XTraining.dot(Theta)
    Yprob = softmax(logits)
    entropy = -np.mean(np.sum(oneHotYTraining * np.log(Yprob + epsilon), axis=1))
    l2Loss = 1/2 * np.sum(np.square(Theta[1:]))
    loss = entropy + alpha * l2Loss
    error = Yprob - oneHotYTraining
    gradients = 1/m * XTraining.T.dot(error) + np.r_[np.zeros([1, numOfOutputs]), alpha * Theta[1:]]
    Theta = Theta - eta * gradients
    logits = XValidation.dot(Theta)
    Yprob = softmax(logits)
    entropy = -np.mean(np.sum(oneHotYValidation * np.log(Yprob + epsilon), axis=1))
    l2Loss = 1/2 * np.sum(np.square(Theta[1:]))
    loss = entropy + alpha * l2Loss
    if iteration % 500 == 0:
        print(iteration, loss)
    if loss < bestLoss:
        bestLoss = loss
    else:
        print(iteration - 1, bestLoss)
        print(iteration, loss, "Error increased, Stopping Early")
        break


    ##Model Trained

0 2.183534235145468
3 0.9229714732760785
4 0.9441280062783698 Error increased, Stopping Early


In [17]:
Theta #Model Parameters

array([[ 0.61567478, -0.1062535 , -0.21366086],
       [-0.29183995,  0.30111364,  0.01786701],
       [ 0.61441884,  0.20956269,  1.22075298]])

In [18]:
#Using Numpy to determine the accuracy of the model
logits = XValidation.dot(Theta)
Yprob = softmax(logits)
predictions = np.argmax(Yprob, axis=1)

score = np.mean(predictions == yValidation)
score

0.5666666666666667

In [19]:
# After multiple runs, with different choices for validation sets and such
# Models created were able to obtain anywhere from 20 - 100 percent accuracy.
# This is caused by the early stopping. If the model starts by moving away from
# The optimal, early stopping will need to be rerun

In [20]:
logits = XTest.dot(Theta)
Yprob = softmax(logits)
predictions = np.argmax(Yprob, axis=1)

score = np.mean(predictions == yTest)
score

0.6666666666666666

In [ ]:
# The results on the test set are similar, sometimes reaching 100 accuracy